server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankAccount
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddlAuto: update

  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankAccConsumer
      auto-offset-reset: earliest
      key-deserializer: com.apache.kafka.common.serialization.StringDeSerializer
      value-deserializer: com.apache.kafka.support.serializer.JsonDeSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"




